# Generated by Django 5.0.1 on 2024-02-21 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bloodgroup',
            new_name='blood_group',
        ),
    ]
