# Generated by Django 5.0.1 on 2024-03-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_contact_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
