# Generated by Django 5.0.1 on 2024-03-14 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_addtocart_orederlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addtocart',
            old_name='email',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orederlist',
            old_name='email',
            new_name='user',
        ),
    ]
