# Generated by Django 5.0.3 on 2024-03-28 04:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_addtocart_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderlist',
            options={'ordering': ['-updated', '-created']},
        ),
        migrations.AddField(
            model_name='orderlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
