# Generated by Django 5.0.3 on 2024-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orderlist_options_orderlist_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='Key_Ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='Safety_Information',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='key_benifits',
            field=models.TextField(blank=True),
        ),
    ]
