# Generated by Django 5.0.3 on 2024-05-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_rename_phonenumber_profile_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addtocart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
