# Generated by Django 5.0.3 on 2024-05-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_addtocart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
