# Generated by Django 5.0.3 on 2024-05-08 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rozorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('cartid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.addtocart')),
            ],
        ),
    ]
